### PR TITLE
Fix for "Empty transcription causes error for digitalpaperedit transcripts #228"

### LINKED ISSUE #228: Empty transcription causes error for digitalpaperedit transcripts
**Describe the bug**

When the `transcriptData` is empty like so:
```
{
  words: [],
  paragraphs: []
}
```
it throws an error.

**To Reproduce**
1. Insert empty transcript data as above
2. see error

**Expected behavior**
Empty transcript shouldn't be considered an error.

**Screenshots**
Screenshot 2020-04-20 at 14 43 48

Screenshot 2020-04-20 at 14 44 00

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by emettely**
**Is your Pull Request request related to another [issue](https://github.com/bbc/react-transcript-editor/issues) in this repository ?**      
Fixes #228 

**Describe what the PR does**    
Screenshot 2020-04-20 at 16 14 24

**State whether the PR is ready for review or whether it needs extra work**    
Ready

**Additional context**

### CODE REVIEW

File: packages/stt-adapters/digital-paper-edit/index.js [hunk 1]
```diff
@@ -3,74 +3,68 @@
...
-          start: paragraph.words[0].start
-        },
-        // the entities as ranges are each word in the space-joined text,
-        // so it needs to be compute for each the offset from the beginning of the paragraph and the length
-        entityRanges: generateEntitiesRanges(paragraph.words, 'text') // wordAttributeName
-      };
-      results.push(draftJsContentBlockParagraph);
+  const results = wordsByParagraphs.map((paragraph, i) => {
+    if (!paragraph.speaker) {
+      paragraph.speaker = `TBC ${ i }`;
```
Comment (allishultes) [inline packages/stt-adapters/digital-paper-edit/index.js:64]: Nice 👍

File: packages/stt-adapters/digital-paper-edit/index.js [hunk 2]
```diff
@@ -3,74 +3,68 @@
...
+    paragraph.text.push(word.text);
+
     // if word contains punctuation
     if (/[.?!]/.test(word.text)) {
-      paragraph.words.push(word);
-      paragraph.text.push(word.text);
       paragraph.text = paragraph.text.join(' ');
       results.push(paragraph);
       // reset paragraph
       paragraph = { words: [], text: [] };
```
Comment (allishultes) [inline packages/stt-adapters/digital-paper-edit/index.js:26]: Since you have to reset this each time, could you just define `paragraph` for the first time inside the `forEach` loop?

Comment (emettely) [reply packages/stt-adapters/digital-paper-edit/index.js:26]: good point
